modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/daedalus4096/PrimalMagic/issues"
license="MIT License"

[[mods]]
modId="primalmagic"
version="${file.jarVersion}"
displayName="Primal Magic"
#updateJSONURL=""
#displayURL=""
credits="Thanks to Lorelli, Quinloki, and DaRetroThaumaturge for the art!"
authors="Daedalus4096"
description='''Harness the magic of the primal sources of the land.'''

[[dependencies.primalmagic]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
