modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/daedalus4096/PrimalMagick/issues"
license="MIT License"

[[mods]]
modId="primalmagick"
version="${file.jarVersion}"
displayName="Primal Magick"
#updateJSONURL=""
#displayURL=""
credits="Thanks to Lorelli, Quinloki, and DaRetroThaumaturge for the art!"
authors="Daedalus4096"
description='''Harness the magick of the primal sources of the land.'''

[[dependencies.primalmagick]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
